name: "DEFAULT"   # MUST BE DEFAULT
import_path: "default.yaml"

params:
  retrain: False # Start training a new model if True. Continue training the most recent version of the model if False.
  task:
    task: mesh
    dataset: flag_minimal
    rollout_split: valid
    batch_size: 1
    epochs: 5
    n_timesteps: 16
    trajectories: 10
    mode: all
    prefetch_factor: 1
    test:
      trajectories: 2 # Number of trajectories that are going to be used to compute the validation loss during evaluation
      rollouts: 2 # Number of trajectories that are going to be used to compute the rollout loss during evaluation
      n_step_rollouts: 2 # Number of trajectories that are going to be used to compute the n_step_loss during evaluation
      n_steps: 10
    validation:
      trajectories: 2 # Number of trajectories that are going to be used to compute the validation loss during training
      rollouts: 2 # Number of trajectories that are going to be used to compute the rollout loss during training
      n_steps: 10
      n_step_rollouts: 2
      n_viz: 2
  model:
    field: world_pos
    history: True
    size: 3
    noise: 0.003
    gamma: 0.9
    scheduler_epoch: 10
    aggregation: pna
    learning_rate: 1.0e-4
    message_passing_steps: 1
    use_global: False
    heterogeneous: False
  logging:
    wandb_mode: online
  random_seed: 0
