name: "DEFAULT"   # MUST BE DEFAULT
import_path: "default.yaml"

random_seed: 115
retrain: False # Start training a new model if True. Continue training the most recent version of the model if False.
wandb_mode: online
directory: deformable_plate

task:
  task: trapez # trapez/poisson
  model: supervised # mgn/supervised/self-supervised
  ggns: False # T/F
  recurrence: True # None/name now T/F
  sequence: 5
  poisson_ratio: False # Link to use global with model
  learning_rate: 5.0e-4
  batch_size: 32
  trajectories: 675
  n_timesteps: 50
  epochs: 200
  pretraining: 150

  test:
    trajectories: 10 # Number of trajectories that are going to be used to compute the validation loss during evaluation
    rollouts: 10 # Number of trajectories that are going to be used to compute the rollout loss during evaluation
    n_step_rollouts: 1 # Number of trajectories that are going to be used to compute the n_step_loss during evaluation
    n_steps: 10

  validation:
    interval: 10
    trajectories: 135 # Number of trajectories that are going to be used to compute the validation loss during training
    rollouts: 135 # Number of trajectories that are going to be used to compute the rollout loss during training
    n_steps: 10
    n_step_rollouts: 20
    n_viz: 5

model:
  feature_norm: False
  layer_norm: False
  layers: 1
  noise: 0.01
  pc_noise: 0.0
  aggregation: mean
  message_passing_steps: 5
  heterogeneous: False
  use_global: True
