name: "DEFAULT"   # MUST BE DEFAULT
import_path: "default.yaml"

params:
  retrain: False # Start training a new model if True. Continue training the most recent version of the model if False.
  task:
    task: alternating
    model: trapez
    sequence: 1
    dataset: deformable_plate
    rollout_split: valid
    batch_size: 32
    epochs: 200
    n_timesteps: 50
    trajectories: 675
    mode: all
    prefetch_factor: 1
    test:
      trajectories: 10 # Number of trajectories that are going to be used to compute the validation loss during evaluation
      rollouts: 10 # Number of trajectories that are going to be used to compute the rollout loss during evaluation
      n_step_rollouts: 1 # Number of trajectories that are going to be used to compute the n_step_loss during evaluation
      n_steps: 10
    validation:
      interval: 10
      trajectories: 135 # Number of trajectories that are going to be used to compute the validation loss during training
      rollouts: 135 # Number of trajectories that are going to be used to compute the rollout loss during training
      n_steps: 10
      n_step_rollouts: 20
      n_viz: 5
  model:
    feature_norm: False
    layer_norm: False
    layers: 1
    size: 2
    noise: 0.01
    pc_noise: 0.0
    pc_frequency: 1
    mgn: True
    poisson_ratio: False
    scheduler_epoch: 10
    aggregation: mean
    learning_rate: 5.0e-4
    message_passing_steps: 5
    use_global: True
    heterogeneous: False
  logging:
    wandb_mode: online
  random_seed: 115